#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)
fpath=("/usr/local/share/zsh-completions" $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Start rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# The Fuck (suggests corrections)
# eval "$(thefuck --alias)"

# Paths
# /Users/samturner/.rbenv/shims
# /Users/samturner/.composer/vendor/bin
# /Users/samturner/.rbenv/bin
# /Users/samturner/.npm-packages/bin


export PATH=${ZDOTDIR:-$HOME}/.composer/vendor/bin:$PATH
# export PATH=${ZDOTDIR:-$HOME}/.npm-packages/bin:$PATH
## Homebrew
# export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## NPM
export PATH=${ZDOTDIR:-$HOME}/.node/bin:$PATH

# Set NODE_PATH for NodeJS
export NODE_PATH=${ZDOTDIR:-$HOME}/.node/lib/node_modules:$NODE_PATH



# 10 second wait if you do something that will delete everything.
setopt RM_STAR_WAIT

# Sublime
export EDITOR="subl -n -w"
setopt IGNORE_EOF



test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# PATH="/Users/samturner/perl5/bin${PATH:+:${PATH}}"; export PATH;
# PERL5LIB="/Users/samturner/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
# PERL_LOCAL_LIB_ROOT="/Users/samturner/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
# PERL_MB_OPT="--install_base \"/Users/samturner/perl5\""; export PERL_MB_OPT;
# PERL_MM_OPT="INSTALL_BASE=/Users/samturner/perl5"; export PERL_MM_OPT;
